### ISSUE TITLE
为什么把v1.2.2版本删了？

### ISSUE THREAD

**Issue by masayil** [stars-labs/heco-chain#61]
12月9号发布了v1.2.2版本，在12月10号我看到版本回退到了v1.2.1。我需要把运行的节点版本也从v1.2.2回退到v1.2.1吗？

**Comment by zzyalbert** [comment]
We found some issue in that version in terms of private chain, so we reverted back immediately.

Now we have release v1.2.2 again after resolved that issue. 

Please update to the latest version, sorry for the inconvenience
