### ISSUE TITLE
Unable to retrieve the latest block information using web3js

### ISSUE THREAD

**Issue by dandavid3000** [stars-labs/heco-chain#67]
Hi,

I try to get the latest block and it always returns me value 0.
In addition, it seems that I cannot retrieve transaction receipts neither for the latest blocks (return is null). I can only get it 5-10 minutes later.

From the node log file , I saw it written :

Imported new block headers count=1 elapsed=1.795ms number=17,394,889 hash=794b4e..b05617

The number seems to be the latest block but I cannot retrieve the information. I used SyncMode snap to run my node.
What should I do in this case to have a full and instant access to node data?

Thanks.

**Comment by ken0x4b656e** [comment]
It will be that your node is still syncing, the snap-sync is not done yet.
You should wait until the `eth_syncing` returns `false`, then your node will be ready for use.

**Comment by dandavid3000** [comment]
Thank you. I let it run and now everything is fully synced.
